//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcmMobileShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CHITIETHOADON
    {
        public int IdctHD { get; set; }
        public Nullable<int> IdHD { get; set; }
        public Nullable<int> IdctSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<double> SoLuongBan { get; set; }
        public Nullable<double> GiaBan { get; set; }
    
        public virtual tb_CT_SANPHAM tb_CT_SANPHAM { get; set; }
        public virtual tb_HOADON tb_HOADON { get; set; }
    }
}
